In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import warnings
warnings.filterwarnings('ignore' )


In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib
sns.set_style('darkgrid')
import warnings
import re
import string
pun = string.punctuation
import nltk
from nltk.corpus import stopwords
stopword = stopwords.words('english')
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
nltk.download('omw-1.4')
nltk.download('punkt')

Using matplotlib backend: <object object at 0x000001B8B2FA47F0>


[nltk_data] Downloading package omw-1.4 to C:\Users\Sumeet
[nltk_data]     Maheshwari\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Sumeet
[nltk_data]     Maheshwari\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
guardian = pd.read_csv('guardian_headlines.csv')
cnbc = pd.read_csv("cnbc_headlines.csv")
reuter = pd.read_csv("reuters_headlines.csv")

In [4]:
guardian.head()

Time                                          Headlines
0  18-Jul-20   Johnson is asking Santa for a Christmas recovery
1  18-Jul-20  ‘I now fear the worst’: four grim tales of wor...
2  18-Jul-20  Five key areas Sunak must tackle to serve up e...
3  18-Jul-20  Covid-19 leaves firms ‘fatally ill-prepared’ f...
4  18-Jul-20  The Week in Patriarchy  \n\n\n  Bacardi's 'lad...

In [5]:
guardian.shape

(17800, 2)

In [6]:
guardian.columns

Index(['Time', 'Headlines'], dtype='object')

In [7]:
guardian.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17800 entries, 0 to 17799
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Time       17800 non-null  object
 1   Headlines  17800 non-null  object
dtypes: object(2)
memory usage: 278.2+ KB


In [8]:
guardian.duplicated().sum()

0

In [9]:
guardian.isnull().sum()

Time         0
Headlines    0
dtype: int64

# Basic EDA on CNBC News Headlines

In [10]:
cnbc.head()

Headlines  \
0  Jim Cramer: A better way to invest in the Covi...   
1     Cramer's lightning round: I would own Teradyne   
2                                                NaN   
3  Cramer's week ahead: Big week for earnings, ev...   
4  IQ Capital CEO Keith Bliss says tech and healt...   

                             Time  \
0   7:51  PM ET Fri, 17 July 2020   
1   7:33  PM ET Fri, 17 July 2020   
2                             NaN   
3   7:25  PM ET Fri, 17 July 2020   
4   4:24  PM ET Fri, 17 July 2020   

                                         Description  
0  "Mad Money" host Jim Cramer recommended buying...  
1  "Mad Money" host Jim Cramer rings the lightnin...  
2                                                NaN  
3  "We'll pay more for the earnings of the non-Co...  
4  Keith Bliss, IQ Capital CEO, joins "Closing Be...

In [11]:
cnbc.shape

(3080, 3)

In [12]:
cnbc.columns

Index(['Headlines', 'Time', 'Description'], dtype='object')

In [13]:
cnbc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3080 entries, 0 to 3079
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Headlines    2800 non-null   object
 1   Time         2800 non-null   object
 2   Description  2800 non-null   object
dtypes: object(3)
memory usage: 72.3+ KB


In [14]:
cnbc.isnull().sum()

Headlines      280
Time           280
Description    280
dtype: int64

In [15]:
cnbc.duplicated().sum()

279

In [16]:
# droping the duplicated rows
cnbc = cnbc.drop_duplicates()

In [17]:
cnbc.dropna(inplace=True)

In [18]:
cnbc.shape

(2800, 3)

# Basic EDA On reuters_headlines

In [19]:
reuter.head()

Headlines         Time  \
0  TikTok considers London and other locations fo...  Jul 18 2020   
1  Disney cuts ad spending on Facebook amid growi...  Jul 18 2020   
2  Trail of missing Wirecard executive leads to B...  Jul 18 2020   
3  Twitter says attackers downloaded data from up...  Jul 18 2020   
4  U.S. Republicans seek liability protections as...  Jul 17 2020   

                                         Description  
0  TikTok has been in discussions with the UK gov...  
1  Walt Disney  has become the latest company to ...  
2  Former Wirecard  chief operating officer Jan M...  
3  Twitter Inc said on Saturday that hackers were...  
4  A battle in the U.S. Congress over a new coron...

In [20]:
reuter.shape

(32770, 3)

In [21]:
reuter.columns

Index(['Headlines', 'Time', 'Description'], dtype='object')

In [22]:
reuter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32770 entries, 0 to 32769
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Headlines    32770 non-null  object
 1   Time         32770 non-null  object
 2   Description  32770 non-null  object
dtypes: object(3)
memory usage: 768.2+ KB


In [23]:
reuter.isnull().sum()

Headlines      0
Time           0
Description    0
dtype: int64

In [24]:
reuter.duplicated().sum()

55

In [25]:
# drop the duplicated values:
reuter.drop_duplicates(inplace = True)

# Text Preprocessing

In [26]:
def textpreprocessing(text):
    text = text.lower()# lowercase 
    # removing puncuation 
    for i in pun:
        text = text.replace(i,'')
    #removing stop words
    stop = set(stopwords.words('english'))
    text_token = word_tokenize(text)
    word = [word for word in text_token if word not in stop]
    
    # stremming 
    
    poster_stem = PorterStemmer()
    word = [poster_stem.stem(w) for w in word ]
    
    #lemmitizing
    lem= WordNetLemmatizer()
    text= [lem.lemmatize(word,'v')for word in word if not word in stop]
    
    return ' '.join(text)
    

# SENTIMENT ANAYSIS


In [27]:
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to C:\Users\Sumeet
[nltk_data]     Maheshwari\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [28]:
#fuction to decide sentiment as positive, negative and neutral
def sentiment(score):
    if score < 0.0:
        return 'negative'
    if score == 0.0:
        return 'neutral'
    else:
        return 'positive'
    

In [29]:
# concatenate cnbc headlines dataset and reuters headline dataset
new_df = pd.concat([cnbc,reuter],axis=0)

In [30]:
new_df.head()

Headlines  \
0  Jim Cramer: A better way to invest in the Covi...   
1     Cramer's lightning round: I would own Teradyne   
3  Cramer's week ahead: Big week for earnings, ev...   
4  IQ Capital CEO Keith Bliss says tech and healt...   
5  Wall Street delivered the 'kind of pullback I'...   

                             Time  \
0   7:51  PM ET Fri, 17 July 2020   
1   7:33  PM ET Fri, 17 July 2020   
3   7:25  PM ET Fri, 17 July 2020   
4   4:24  PM ET Fri, 17 July 2020   
5   7:36  PM ET Thu, 16 July 2020   

                                         Description  
0  "Mad Money" host Jim Cramer recommended buying...  
1  "Mad Money" host Jim Cramer rings the lightnin...  
3  "We'll pay more for the earnings of the non-Co...  
4  Keith Bliss, IQ Capital CEO, joins "Closing Be...  
5  "Look for the stocks of high-quality companies...

In [31]:
new_df.shape

(35515, 3)

In [32]:
new_df['Description'] = new_df['Description'].apply(textpreprocessing)

In [33]:
new_df.head()

Headlines  \
0  Jim Cramer: A better way to invest in the Covi...   
1     Cramer's lightning round: I would own Teradyne   
3  Cramer's week ahead: Big week for earnings, ev...   
4  IQ Capital CEO Keith Bliss says tech and healt...   
5  Wall Street delivered the 'kind of pullback I'...   

                             Time  \
0   7:51  PM ET Fri, 17 July 2020   
1   7:33  PM ET Fri, 17 July 2020   
3   7:25  PM ET Fri, 17 July 2020   
4   4:24  PM ET Fri, 17 July 2020   
5   7:36  PM ET Thu, 16 July 2020   

                                         Description  
0  mad money host jim cramer recommend buy four c...  
1  mad money host jim cramer ring lightn round be...  
3  well pay earn noncovid compani lancet publish ...  
4  keith bliss iq capit ceo join close bell talk ...  
5  look stock highqual compani go lower even thou...

In [34]:
# analyze polarity score of values in description and  add new column of it in dataset
ds_score=[]
for value in new_df['Description'].values:
    ds_score.append(sid.polarity_scores(value)['compound'])
new_df['ds_score'] = ds_score


In [35]:
new_df.head()

Headlines  \
0  Jim Cramer: A better way to invest in the Covi...   
1     Cramer's lightning round: I would own Teradyne   
3  Cramer's week ahead: Big week for earnings, ev...   
4  IQ Capital CEO Keith Bliss says tech and healt...   
5  Wall Street delivered the 'kind of pullback I'...   

                             Time  \
0   7:51  PM ET Fri, 17 July 2020   
1   7:33  PM ET Fri, 17 July 2020   
3   7:25  PM ET Fri, 17 July 2020   
4   4:24  PM ET Fri, 17 July 2020   
5   7:36  PM ET Thu, 16 July 2020   

                                         Description  ds_score  
0  mad money host jim cramer recommend buy four c...    0.2500  
1  mad money host jim cramer ring lightn round be...   -0.4939  
3  well pay earn noncovid compani lancet publish ...    0.5574  
4  keith bliss iq capit ceo join close bell talk ...    0.7096  
5  look stock highqual compani go lower even thou...   -0.6597

In [36]:
new_df['sentiment']= new_df['ds_score'].apply(sentiment) 

In [37]:
new_df.head()

Headlines  \
0  Jim Cramer: A better way to invest in the Covi...   
1     Cramer's lightning round: I would own Teradyne   
3  Cramer's week ahead: Big week for earnings, ev...   
4  IQ Capital CEO Keith Bliss says tech and healt...   
5  Wall Street delivered the 'kind of pullback I'...   

                             Time  \
0   7:51  PM ET Fri, 17 July 2020   
1   7:33  PM ET Fri, 17 July 2020   
3   7:25  PM ET Fri, 17 July 2020   
4   4:24  PM ET Fri, 17 July 2020   
5   7:36  PM ET Thu, 16 July 2020   

                                         Description  ds_score sentiment  
0  mad money host jim cramer recommend buy four c...    0.2500  positive  
1  mad money host jim cramer ring lightn round be...   -0.4939  negative  
3  well pay earn noncovid compani lancet publish ...    0.5574  positive  
4  keith bliss iq capit ceo join close bell talk ...    0.7096  positive  
5  look stock highqual compani go lower even thou...   -0.6597  negative

In [38]:
new_df['sentiment'].value_counts()

positive    15101
negative    12292
neutral      8122
Name: sentiment, dtype: int64

In [39]:
plt.figure(figsize=(15,6))
sns.countplot(new_df['sentiment'])

<AxesSubplot:xlabel='sentiment', ylabel='count'>

In [40]:
new_df['sentiment'].value_counts().plot(kind='bar')
plt.show()

In [41]:
new_df['sentiment'].value_counts().plot(kind='pie',autopct = '%1.1f%%')
plt.show()

In [42]:
x = new_df['Description']
y = new_df['sentiment']

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y, test_size = 0.1,random_state = 212)

In [44]:
X_train.shape ,y_train.shape,X_test.shape ,y_test.shape

((31963,), (31963,), (3552,), (3552,))

In [45]:
%%time 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report,f1_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import LogisticRegression

CPU times: total: 0 ns
Wall time: 2 ms


# LINEAR SUPPORT VECTOR MACHINE


In [46]:
%%time
# creating a pipeline
pipe_lsvm = Pipeline([('tfidf',TfidfVectorizer()),('model',LinearSVC())])
# fit data into pipeline
model_lsvm = pipe_lsvm.fit(X_train,y_train)

# predict on test dataset
prediction = model_lsvm.predict(X_test)

print("MODEL: LINEAR SVC")

# print accuracy score
print("accuarcy score: ", accuracy_score(y_test, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test, prediction))

#print classification report
print(classification_report(y_test, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test, prediction),annot = True,cmap ='Blues')

MODEL: LINEAR SVC
accuarcy score:  0.9324324324324325
Confusion matrix:  [[1122   46   71]
 [  24  757   23]
 [  46   30 1433]]
              precision    recall  f1-score   support

    negative       0.94      0.91      0.92      1239
     neutral       0.91      0.94      0.92       804
    positive       0.94      0.95      0.94      1509

    accuracy                           0.93      3552
   macro avg       0.93      0.93      0.93      3552
weighted avg       0.93      0.93      0.93      3552

CPU times: total: 1.47 s
Wall time: 1.47 s


<AxesSubplot:>

# LOGISTIC REGRESSION

In [47]:
%%time
pipe_lr = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('log_reg', LogisticRegression())])

model_lr =pipe_lr.fit(X_train, y_train)

# predict on test dataset
prediction = model_lr.predict(X_test)

print("MODEL: LOGISTIC REGRESSION")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test, prediction))

#print classification report
print(classification_report(y_test, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test, prediction),annot = True,cmap ='Blues')

MODEL: LOGISTIC REGRESSION
accuarcy score:  0.8992117117117117
Confusion matrix:  [[1071   70   98]
 [  37  733   34]
 [  70   49 1390]]
              precision    recall  f1-score   support

    negative       0.91      0.86      0.89      1239
     neutral       0.86      0.91      0.89       804
    positive       0.91      0.92      0.92      1509

    accuracy                           0.90      3552
   macro avg       0.89      0.90      0.90      3552
weighted avg       0.90      0.90      0.90      3552

CPU times: total: 9.28 s
Wall time: 2.9 s


<AxesSubplot:>

# MULTINOMIAL NAIVE BAYES


In [48]:
%%time 
from sklearn.naive_bayes import MultinomialNB
# creating a pipeline

pipe_mnb = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('MNB', MultinomialNB())])
# traing a model
model_mnb = pipe_mnb.fit(X_train,y_train)
# prediction
prediction = model_mnb.predict(X_test)
print("MODEL: MultiNomial Naive Bayes")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test, prediction))

#print classification report
print(classification_report(y_test, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test, prediction),annot = True,cmap ='Blues')


MODEL: MultiNomial Naive Bayes
accuarcy score:  0.6396396396396397
Confusion matrix:  [[ 806    8  425]
 [ 149   84  571]
 [ 122    5 1382]]
              precision    recall  f1-score   support

    negative       0.75      0.65      0.70      1239
     neutral       0.87      0.10      0.19       804
    positive       0.58      0.92      0.71      1509

    accuracy                           0.64      3552
   macro avg       0.73      0.56      0.53      3552
weighted avg       0.70      0.64      0.59      3552

CPU times: total: 844 ms
Wall time: 852 ms


<AxesSubplot:>

# BERNOULLI NAIVE BAYES

In [49]:
%%time
from sklearn.naive_bayes import BernoulliNB
pipe_mnb = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('BNB', BernoulliNB())])
# traing a model
model_mnb = pipe_mnb.fit(X_train,y_train)
# prediction
prediction = model_mnb.predict(X_test)
print("MODEL: Bernolli Naive Bayes")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test, prediction))

#print classification report
print(classification_report(y_test, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test, prediction),annot = True,cmap ='Blues')


MODEL: Bernolli Naive Bayes
accuarcy score:  0.7387387387387387
Confusion matrix:  [[ 927   57  255]
 [ 139  474  191]
 [ 213   73 1223]]
              precision    recall  f1-score   support

    negative       0.72      0.75      0.74      1239
     neutral       0.78      0.59      0.67       804
    positive       0.73      0.81      0.77      1509

    accuracy                           0.74      3552
   macro avg       0.75      0.72      0.73      3552
weighted avg       0.74      0.74      0.74      3552

CPU times: total: 828 ms
Wall time: 836 ms


<AxesSubplot:>

# GradientBoostingClassifier

In [50]:
%%time
# pipeline creation 
# 1. CountVectorizer
# 2. TfidTransformer
# 3. GradientBoostingClassifier

from sklearn.ensemble import GradientBoostingClassifier


# Fit the pipeline to the data
pipe_mnb = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('grad_boost', GradientBoostingClassifier())])
# traing a model
model_mnb = pipe_mnb.fit(X_train,y_train)
# prediction
prediction = model_mnb.predict(X_test)
print("MODEL: Gradient Boosting Classifer")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test, prediction))

#print classification report
print(classification_report(y_test, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test, prediction),annot = True,cmap ='Blues')


MODEL: Gradient Boosting Classifer
accuarcy score:  0.84375
Confusion matrix:  [[ 917  151  171]
 [  11  782   11]
 [  65  146 1298]]
              precision    recall  f1-score   support

    negative       0.92      0.74      0.82      1239
     neutral       0.72      0.97      0.83       804
    positive       0.88      0.86      0.87      1509

    accuracy                           0.84      3552
   macro avg       0.84      0.86      0.84      3552
weighted avg       0.86      0.84      0.84      3552

CPU times: total: 59.8 s
Wall time: 1min


<AxesSubplot:>

# XGBOOST CLASSIFICATION MODEL

In [51]:
%%time
# pipeline creation 
# 1. CountVectorizer
# 2. TfidTransformer
# 3. GradientBoostingClassifier

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder


# Fit the pipeline to the data
xg_boost_ds = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('xgb', XGBClassifier())])

encoder = LabelEncoder()
enc_train = encoder.fit_transform(y_train)
enc_test = encoder.fit_transform(y_test)

xg_boost_ds.fit(X_train, enc_train)
# prediction
prediction = xg_boost_ds.predict(X_test)
print("MODEL: xgboost")



# print accuracy score
print("accuarcy score: ", accuracy_score(enc_test, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(enc_test, prediction))

#print classification report
print(classification_report(enc_test, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(enc_test, prediction),annot = True,cmap ='Blues')

MODEL: xgboost
accuarcy score:  0.8890765765765766
Confusion matrix:  [[1006  118  115]
 [  11  783   10]
 [  52   88 1369]]
              precision    recall  f1-score   support

           0       0.94      0.81      0.87      1239
           1       0.79      0.97      0.87       804
           2       0.92      0.91      0.91      1509

    accuracy                           0.89      3552
   macro avg       0.88      0.90      0.89      3552
weighted avg       0.90      0.89      0.89      3552

CPU times: total: 2min 33s
Wall time: 20.5 s


<AxesSubplot:>

In [97]:
# helper function for comparing models matric

def metrics_comparison(model_objects, model_names, X_test, y_test, enc_test):
    
    # create a dataframe with column matric and metric name as value
    metrics_df = pd.DataFrame(columns=['model_names','accuracy','precision','recall','f1_score'])
    metrics_df['model_names'] = model_names
   
    # then predict on the test set
    metrics_df['accuracy'] = [accuracy_score(y_test, model.predict(X_test)) if model != xg_boost_ds else accuracy_score(enc_test, model.predict(X_test)) for model in model_objects]
    metrics_df['precision'] = [precision_score(y_test, model.predict(X_test),average='weighted') if model != xg_boost_ds else precision_score(enc_test, model.predict(X_test), average='weighted') for model in model_objects]
    metrics_df['recall'] = [recall_score(y_test, model.predict(X_test),average='weighted') if model != xg_boost_ds else recall_score(enc_test, model.predict(X_test),average='weighted') for model in model_objects]
    metrics_df['f1_score'] = [f1_score(y_test, model.predict(X_test),average='weighted') if model != xg_boost_ds else f1_score(enc_test, model.predict(X_test), average='weighted') for model in model_objects]
    
    return metrics_df

In [53]:
# list of model objects
model_objects = [model_lsvm, model_lr, model_mnb, model_mnb, model_mnb, xg_boost_ds]

# list of model names
model_names = ['LinearSVC', 'LogRegression','MultinomialNB','BernoulliNB','GradientBoost','XGBoost']

# print the comparison of models
met_df = metrics_comparison(model_objects,model_names, X_test, y_test, enc_test)
met_df

model_names  accuracy  precision    recall  f1_score
0      LinearSVC  0.932432   0.932712  0.932432  0.932372
1  LogRegression  0.899212   0.899857  0.899212  0.899162
2  MultinomialNB  0.843750   0.858756  0.843750  0.843596
3    BernoulliNB  0.843750   0.858756  0.843750  0.843596
4  GradientBoost  0.843750   0.858756  0.843750  0.843596
5        XGBoost  0.889077   0.896751  0.889077  0.889118

In [54]:
pred = model_lsvm.predict(X_test)
pred

array(['negative', 'neutral', 'positive', ..., 'positive', 'positive',
       'positive'], dtype=object)

In [55]:
pred = pd.DataFrame(pred, columns=['predictions'])

In [56]:
pred.head()

predictions
0    negative
1     neutral
2    positive
3    positive
4    negative

# Now working with headlines + description

In [57]:
new_df

Headlines  \
0      Jim Cramer: A better way to invest in the Covi...   
1         Cramer's lightning round: I would own Teradyne   
3      Cramer's week ahead: Big week for earnings, ev...   
4      IQ Capital CEO Keith Bliss says tech and healt...   
5      Wall Street delivered the 'kind of pullback I'...   
...                                                  ...   
32765  Malaysia says never hired British data firm at...   
32766  Prosecutors search Volkswagen headquarters in ...   
32767   McDonald's sets greenhouse gas reduction targets   
32768  Pratt & Whitney to deliver spare A320neo engin...   
32769  UK will always consider ways to improve data l...   

                                 Time  \
0       7:51  PM ET Fri, 17 July 2020   
1       7:33  PM ET Fri, 17 July 2020   
3       7:25  PM ET Fri, 17 July 2020   
4       4:24  PM ET Fri, 17 July 2020   
5       7:36  PM ET Thu, 16 July 2020   
...                               ...   
32765                     Mar 20 2018   
32766                     Mar 20 2018   
32767                     Mar 20 2018   
32768                     Mar 20 2018   
32769                     Mar 20 2018   

                                             Description  ds_score sentiment  
0      mad money host jim cramer recommend buy four c...    0.2500  positive  
1      mad money host jim cramer ring lightn round be...   -0.4939  negative  
3      well pay earn noncovid compani lancet publish ...    0.5574  positive  
4      keith bliss iq capit ceo join close bell talk ...    0.7096  positive  
5      look stock highqual compani go lower even thou...   -0.6597  negative  
...                                                  ...       ...       ...  
32765  malaysian govern rule parti tuesday deni ever ...    0.0000   neutral  
32766  german prosecutor say tuesday search volkswage...    0.0000   neutral  
32767  mcdonald corp tuesday announc approv scienc ba...   -0.2732  negative  
32768  pratt whitney soon begin deliveri spare engin ...   -0.3818  negative  
32769  britain consid suggest give bodi charg uphold ...    0.3818  positive  

[35515 rows x 5 columns]

In [60]:
headline_df = new_df[['Headlines','Time']]

In [61]:
headline_df.head()

Headlines  \
0  Jim Cramer: A better way to invest in the Covi...   
1     Cramer's lightning round: I would own Teradyne   
3  Cramer's week ahead: Big week for earnings, ev...   
4  IQ Capital CEO Keith Bliss says tech and healt...   
5  Wall Street delivered the 'kind of pullback I'...   

                             Time  
0   7:51  PM ET Fri, 17 July 2020  
1   7:33  PM ET Fri, 17 July 2020  
3   7:25  PM ET Fri, 17 July 2020  
4   4:24  PM ET Fri, 17 July 2020  
5   7:36  PM ET Thu, 16 July 2020

In [63]:
# apply preprocessing in headline 
headline_df['Headlines']=headline_df['Headlines'].apply(textpreprocessing)

In [65]:
ds_score=[]
for value in headline_df['Headlines'].values:
    ds_score.append(sid.polarity_scores(value)['compound'])
headline_df['ds_score'] = ds_score

In [68]:
headline_df.head()

Headlines  \
0  jim cramer better way invest covid19 vaccin go...   
1                  cramer lightn round would teradyn   
3  cramer week ahead big week earn even bigger we...   
4  iq capit ceo keith bliss say tech healthcar ralli   
5  wall street deliv kind pullback ive wait jim c...   

                             Time  ds_score sentiment  
0   7:51  PM ET Fri, 17 July 2020    0.4404  positive  
1   7:33  PM ET Fri, 17 July 2020    0.0000   neutral  
3   7:25  PM ET Fri, 17 July 2020    0.0000   neutral  
4   4:24  PM ET Fri, 17 July 2020    0.5719  positive  
5   7:36  PM ET Thu, 16 July 2020    0.5267  positive

In [78]:
headline_df.shape

(35515, 4)

In [67]:
headline_df['sentiment']= headline_df['ds_score'].apply(sentiment) 

In [69]:
headline_df['sentiment'].value_counts()

neutral     16457
negative     9922
positive     9136
Name: sentiment, dtype: int64

In [71]:
headline_df['sentiment'].value_counts().plot(kind='bar')
plt.show()

In [72]:
headline_df['sentiment'].value_counts().plot(kind='pie',autopct = '%1.1f%%')
plt.show()

In [80]:
X=headline_df['Headlines']
Y=headline_df['sentiment']

In [84]:
from sklearn.model_selection import train_test_split
X_train_head,X_test_head,y_train_head,y_test_head = train_test_split(X,Y, test_size = 0.1,random_state = 212)

In [ ]:
X_train_head.shape ,y_train_head.shape,X_test_head.shape ,y_test_head.shape

# LINEAR SUPPORT VECTOR MACHINE

In [121]:
%%time
# creating a pipeline
pipe_lsvm = Pipeline([('tfidf',TfidfVectorizer()),('model',LinearSVC())])
# fit data into pipeline
model_lsvm_head = pipe_lsvm.fit(X_train_head,y_train_head)

# predict on test dataset
prediction = model_lsvm.predict(X_test_head)

print("MODEL: LINEAR SVC")

# print accuracy score
print("accuarcy score: ", accuracy_score(y_test_head, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test_head, prediction))

#print classification report
print(classification_report(y_test_head, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test_head, prediction),annot = True,cmap ='Blues')

MODEL: LINEAR SVC
accuarcy score:  0.9715653153153153
Confusion matrix:  [[ 922   18   33]
 [   3 1661    3]
 [  27   17  868]]
              precision    recall  f1-score   support

    negative       0.97      0.95      0.96       973
     neutral       0.98      1.00      0.99      1667
    positive       0.96      0.95      0.96       912

    accuracy                           0.97      3552
   macro avg       0.97      0.97      0.97      3552
weighted avg       0.97      0.97      0.97      3552

CPU times: total: 797 ms
Wall time: 791 ms


<AxesSubplot:>

# Logistic regression

In [87]:
%%time
pipe_lr = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('log_reg', LogisticRegression())])

model_lr =pipe_lr.fit(X_train_head, y_train_head)

# predict on test dataset
prediction = model_lr.predict(X_test_head)

print("MODEL: LOGISTIC REGRESSION")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test_head, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test_head, prediction))

#print classification report
print(classification_report(y_test_head, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test_head, prediction),annot = True,cmap ='Blues')

MODEL: LOGISTIC REGRESSION
accuarcy score:  0.9358108108108109
Confusion matrix:  [[ 856   78   39]
 [   2 1662    3]
 [  41   65  806]]
              precision    recall  f1-score   support

    negative       0.95      0.88      0.91       973
     neutral       0.92      1.00      0.96      1667
    positive       0.95      0.88      0.92       912

    accuracy                           0.94      3552
   macro avg       0.94      0.92      0.93      3552
weighted avg       0.94      0.94      0.93      3552

CPU times: total: 6.12 s
Wall time: 1.99 s


<AxesSubplot:>

# MULTINOMIAL NAIVE BAYES

In [89]:
%%time 
from sklearn.naive_bayes import MultinomialNB
# creating a pipeline

pipe_mnb = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('MNB', MultinomialNB())])
# traing a model
model_mnb = pipe_mnb.fit(X_train_head,y_train_head)
# prediction
prediction = model_mnb.predict(X_test_head)
print("MODEL: MultiNomial Naive Bayes")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test_head, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test_head, prediction))

#print classification report
print(classification_report(y_test_head, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test_head, prediction),annot = True,cmap ='Blues')

MODEL: MultiNomial Naive Bayes
accuarcy score:  0.8409346846846847
Confusion matrix:  [[ 758  160   55]
 [  32 1606   29]
 [  85  204  623]]
              precision    recall  f1-score   support

    negative       0.87      0.78      0.82       973
     neutral       0.82      0.96      0.88      1667
    positive       0.88      0.68      0.77       912

    accuracy                           0.84      3552
   macro avg       0.85      0.81      0.82      3552
weighted avg       0.85      0.84      0.84      3552

CPU times: total: 484 ms
Wall time: 472 ms


<AxesSubplot:>

# BERNOULLI NAIVE BAYES

In [90]:
%%time
from sklearn.naive_bayes import BernoulliNB
pipe_mnb = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('BNB', BernoulliNB())])
# traing a model
model_mnb = pipe_mnb.fit(X_train_head,y_train_head)
# prediction
prediction = model_mnb.predict(X_test_head)
print("MODEL: Bernolli Naive Bayes")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test_head, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test_head, prediction))

#print classification report
print(classification_report(y_test_head, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test_head, prediction),annot = True,cmap ='Blues')


MODEL: Bernolli Naive Bayes
accuarcy score:  0.8716216216216216
Confusion matrix:  [[ 844   50   79]
 [ 104 1479   84]
 [  98   41  773]]
              precision    recall  f1-score   support

    negative       0.81      0.87      0.84       973
     neutral       0.94      0.89      0.91      1667
    positive       0.83      0.85      0.84       912

    accuracy                           0.87      3552
   macro avg       0.86      0.87      0.86      3552
weighted avg       0.88      0.87      0.87      3552

CPU times: total: 500 ms
Wall time: 511 ms


<AxesSubplot:>

# GradientBoostingClassifier

In [91]:
%%time
# pipeline creation 
# 1. CountVectorizer
# 2. TfidTransformer
# 3. GradientBoostingClassifier

from sklearn.ensemble import GradientBoostingClassifier


# Fit the pipeline to the data
pipe_mnb = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('grad_boost', GradientBoostingClassifier())])
# traing a model
model_mnb = pipe_mnb.fit(X_train_head,y_train_head)
# prediction
prediction = model_mnb.predict(X_test_head)
print("MODEL: Gradient Boosting Classifer")



# print accuracy score
print("accuarcy score: ", accuracy_score(y_test_head, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(y_test_head, prediction))

#print classification report
print(classification_report(y_test_head, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(y_test_head, prediction),annot = True,cmap ='Blues')


MODEL: Gradient Boosting Classifer
accuarcy score:  0.8333333333333334
Confusion matrix:  [[ 663  260   50]
 [   2 1663    2]
 [  38  240  634]]
              precision    recall  f1-score   support

    negative       0.94      0.68      0.79       973
     neutral       0.77      1.00      0.87      1667
    positive       0.92      0.70      0.79       912

    accuracy                           0.83      3552
   macro avg       0.88      0.79      0.82      3552
weighted avg       0.86      0.83      0.83      3552

CPU times: total: 21.1 s
Wall time: 21.1 s


<AxesSubplot:>

# XGBOOST CLASSIFICATION MODEL

In [92]:
%%time
# pipeline creation 
# 1. CountVectorizer
# 2. TfidTransformer
# 3. GradientBoostingClassifier

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder


# Fit the pipeline to the data
xg_boost_ds = Pipeline([('count_vec', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('xgb', XGBClassifier())])

encoder = LabelEncoder()
enc_train = encoder.fit_transform(y_train_head)
enc_test = encoder.fit_transform(y_test_head)

xg_boost_ds.fit(X_train_head, enc_train)
# prediction
prediction = xg_boost_ds.predict(X_test_head)
print("MODEL: xgboost")



# print accuracy score
print("accuarcy score: ", accuracy_score(enc_test, prediction))

#print confusion matrix
print("Confusion matrix: ", confusion_matrix(enc_test, prediction))

#print classification report
print(classification_report(enc_test, prediction))

# ploting the heatmap of confusion matrix
sns.heatmap(confusion_matrix(enc_test, prediction),annot = True,cmap ='Blues')

MODEL: xgboost
accuarcy score:  0.918918918918919
Confusion matrix:  [[ 817  126   30]
 [   1 1663    3]
 [  28  100  784]]
              precision    recall  f1-score   support

           0       0.97      0.84      0.90       973
           1       0.88      1.00      0.94      1667
           2       0.96      0.86      0.91       912

    accuracy                           0.92      3552
   macro avg       0.94      0.90      0.91      3552
weighted avg       0.92      0.92      0.92      3552

CPU times: total: 1min 9s
Wall time: 9.75 s


<AxesSubplot:>

In [100]:
# helper function for comparing models matric

def metrics_comparison(model_objects, model_names, X_test_head, y_test_head, enc_test):
    
    # create a dataframe with column matric and metric name as value
    metrics_df = pd.DataFrame(columns=['model_names','accuracy','precision','recall','f1_score'])
    metrics_df['model_names'] = model_names
   
    # then predict on the test set
    metrics_df['accuracy'] = [accuracy_score(y_test_head, model.predict(X_test_head)) if model != xg_boost_ds else accuracy_score(enc_test, model.predict(X_test_head)) for model in model_objects]
    metrics_df['precision'] = [precision_score(y_test_head, model.predict(X_test_head),average='weighted') if model != xg_boost_ds else precision_score(enc_test, model.predict(X_test_head), average='weighted') for model in model_objects]
    metrics_df['recall'] = [recall_score(y_test_head, model.predict(X_test_head),average='weighted') if model != xg_boost_ds else recall_score(enc_test, model.predict(X_test_head),average='weighted') for model in model_objects]
    metrics_df['f1_score'] = [f1_score(y_test_head, model.predict(X_test_head),average='weighted') if model != xg_boost_ds else f1_score(enc_test, model.predict(X_test_head), average='weighted') for model in model_objects]
    
    return metrics_df

In [122]:
# list of model objects
model_objects = [model_lsvm_head, model_lr, model_mnb, model_mnb, model_mnb, xg_boost_ds]

# list of model names
model_names = ['LinearSVC', 'LogRegression','MultinomialNB','BernoulliNB','GradientBoost','XGBoost']

# print the comparison of models
met_df = metrics_comparison(model_objects,model_names, X_test_head, y_test_head, enc_test)
met_df

model_names  accuracy  precision    recall  f1_score
0      LinearSVC  0.971565   0.971458  0.971565  0.971441
1  LogRegression  0.935811   0.937000  0.935811  0.934991
2  MultinomialNB  0.833333   0.856464  0.833333  0.828014
3    BernoulliNB  0.833333   0.856464  0.833333  0.828014
4  GradientBoost  0.833333   0.856464  0.833333  0.828014
5        XGBoost  0.918919   0.924090  0.918919  0.917877

In [106]:
pred = model_lsvm.predict(X_test_head)
pred

array(['neutral', 'negative', 'positive', ..., 'neutral', 'positive',
       'neutral'], dtype=object)

In [107]:
pred_headlines = pd.DataFrame(pred, columns=['predictions'])
pred_headlines.head()

predictions
0     neutral
1    negative
2    positive
3     neutral
4     neutral

In [128]:
sent1 = ['Man jailed after defrauding Worle butcher of thousands of pounds']
y_predict = model_lsvm_head.predict(sent1)
y_predict

array(['neutral'], dtype=object)

In [124]:

sent2 =["Finance Ministry releases Rs 9,871 crore to 17 states as grant"]
y_predict = model_lsvm_head.predict(sent2)
y_predict

array(['positive'], dtype=object)

In [119]:
sent3 = ['sensex advance 250 points,nifity50 above17650; bharti airtel ,tata steel rise 1% each']
y_predict = model_lsvm.predict(sent3)
y_predict

array(['neutral'], dtype=object)